name: Recipe App Api CI

on:
  push:
    branches: [ main ]

jobs:
  recipe_app_api_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run Tests
      workdir:
      run: |
        cd app
        python3 ./app/manage.py test
